select nombre from producto;
select nombre,precio from producto;
select * from producto;
select nombre,precio,precio*1.14 from producto;
select nombre,precio as euos, precio*1.14 as dollars from producto;
select upper(nombre),precio from producto;
select lower(nombre),precio from producto;
select nombre, upper(substring(nombre,1,2)) from fabricante;
select nombre,round(precio) from producto;
select nombre,round(precio) from producto;
select codigo_fabricante from producto;
select codigo_fabricante from producto group by codigo_fabricante;
select nombre from fabricante order by nombre asc;
select nombre from fabricante order by nombre desc;
select nombre,precio from producto order by nombre, precio desc;
select nombre from fabricante limit 5;
select nombre from fabricante limit 3,2;
